#lenght, splits examples of romeojuliet para's
txt="Romeo.  Why,  such  is  love\'s  transgression. \nGriefs  of  mine  own  lie  heavy  in  my  breast, \nWhich  thou  wilt  propagate,  to  have  it  prest \nWith  more  of  thine ;  this  love  that  thou  hast  shown \nDoth  add  more  grief  to  too  much  of  mine  own. \nLove  is  a  smoke  rais\'d  with  the  fume  of  sighs : \nBeing  purg\'d,  a  fire  sparkling  in  lovers\'  eyes ; \nBeing  vex\'d,  a  sea  nourish\'d  with  lovers\'  tears ; \nWhat  is  it  else  ?  a  madness  most  discreet, \nA  choking  gall,  and  a  preserving  sweet. \nFarewell,  my  coz. \n\nBenvolio.  Soft !  I  will  go  along ; \n\nAn  if  you  leave  me  so,  you  do  me  wrong. \n\nRomeo.  Tut,  I  have  lost  myself  ;  I  am  not  here : \nThis  is  not  Romeo,  he\'s  some  other  where. \n\nBenvolio.  Tell  me  in  sadness  who  is  that  you  love. \n\nRomeo.  What,  shall  I  groan  and  tell  thee  ? \n\nBenvolio.  Groan  !  why,  no  ; \n\nBut  sadly  tell  me  who. \n\nRomeo.  Bid  a  sick  man  in  sadness  make  his  will; \n\n\n18  ROMEO  AND  JULIET. \n\nAh,  word  ill  urg\'d  to  one  that  is  so  ill ! \nIn  sadness,  cousin,  I  do  love  a  woman. \n\nBenvolio.  I  aini\'d  so  near  when  I  suppos\'d  you  lov\'d. \n\nRomeo.  A  right  good  mark-man  !    And  she\'s  fair  I  love. \n\nBenvolio.  A  right  fair  mark,  fair  coz,  is  soonest  hit. \n\nRomeo.  Well,  in  that  hit  you  miss  :  she\'ll  not  be  hit \nWith  Cupid\'s  arrow  ;  she  hath  Dian\'s  wit. \nAnd,  in  strong  proof  of  chastity  well  arm\'d, \nFrom  love\'s  weak  childish  bow  she  lives  unharm\'d. \nShe  will  not  stay  the  siege  of  loving  terms. \nNor  bide  the  encounter  of  assailing  eyes, \nNor  ope  her  lap  to  saint-seducing  gold ; \n0,  she  is  rich  in  beauty  !  only  poor \nThat,  when  she  dies,  with  beauty  dies  her  store. \n\nBenvolio.  Then  she  hath  sworn  that  she  will  still  live \nchaste  ? "
txt="""Romeo.  Why,  such  is  love\'s  transgression. \nGriefs  of  mine  own  lie  heavy  in  my  breast, \nWhich  thou  wilt  propagate,  to  have  it  prest \nWith  more  of  thine ;  this  love  that  thou  hast  shown \nDoth  add  more  grief  to  too  much  of  mine  own. \nLove  is  a  smoke  rais\'d  with  the  fume  of  sighs : \nBeing  purg\'d,  a  fire  sparkling  in  lovers\'  eyes ; \nBeing  vex\'d,  a  sea  nourish\'d  with  lovers\'  tears ; \nWhat  is  it  else  ?  a  madness  most  discreet, \nA  choking  gall,  and  a  preserving  sweet. \nFarewell,  my  coz. \n\nBenvolio.  Soft !  I  will  go  along ; \n\nAn  if  you  leave  me  so,  you  do  me  wrong. \n\nRomeo.  Tut,  I  have  lost  myself  ;  I  am  not  here : \nThis  is  not  Romeo,  he\'s  some  other  where. \n\nBenvolio.  Tell  me  in  sadness  who  is  that  you  love. \n\nRomeo.  What,  shall  I  groan  and  tell  thee  ? \n\nBenvolio.  Groan  !  why,  no  ; \n\nBut  sadly  tell  me  who. \n\nRomeo.  Bid  a  sick  man  in  sadness  make  his  will; \n\n\n18  ROMEO  AND  JULIET. \n\nAh,  word  ill  urg\'d  to  one  that  is  so  ill ! \nIn  sadness,  cousin,  I  do  love  a  woman. \n\nBenvolio.  I  aini\'d  so  near  when  I  suppos\'d  you  lov\'d. \n\nRomeo.  A  right  good  mark-man  !    And  she\'s  fair  I  love. \n\nBenvolio.  A  right  fair  mark,  fair  coz,  is  soonest  hit. \n\nRomeo.  Well,  in  that  hit  you  miss  :  she\'ll  not  be  hit \nWith  Cupid\'s  arrow  ;  she  hath  Dian\'s  wit. \nAnd,  in  strong  proof  of  chastity  well  arm\'d, \nFrom  love\'s  weak  childish  bow  she  lives  unharm\'d. \nShe  will  not  stay  the  siege  of  loving  terms. \nNor  bide  the  encounter  of  assailing  eyes, \nNor  ope  her  lap  to  saint-seducing  gold ; \n0,  she  is  rich  in  beauty  !  only  poor \nThat,  when  she  dies,  with  beauty  dies  her  store. \n\nBenvolio.  Then  she  hath  sworn  that  she  will  still  live \nchaste  ? """
print("splitting txt line by line:   ",txt.split("\n"))
print("\n")
print("lenght of para's, number of lines are: ",len(txt.split("\n")))
print("\n")
print("appending txt into txt2 in lowercase:","\n")
txt2=[]
for everyword in txt.split():
    txt2.append(everyword.lower())
print("txt2 is:",txt2)


                                                    
