USE [master]
GO

/****** Object:  Database [KCC]    Script Date: 11-09-2025 16:13:25 ******/
CREATE DATABASE [KCC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'KCC', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\KCC.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'KCC_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\KCC_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [KCC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [KCC] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [KCC] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [KCC] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [KCC] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [KCC] SET ARITHABORT OFF 
GO

ALTER DATABASE [KCC] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [KCC] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [KCC] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [KCC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [KCC] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [KCC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [KCC] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [KCC] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [KCC] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [KCC] SET  DISABLE_BROKER 
GO

ALTER DATABASE [KCC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [KCC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [KCC] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [KCC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [KCC] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [KCC] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [KCC] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [KCC] SET RECOVERY FULL 
GO

ALTER DATABASE [KCC] SET  MULTI_USER 
GO

ALTER DATABASE [KCC] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [KCC] SET DB_CHAINING OFF 
GO

ALTER DATABASE [KCC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [KCC] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [KCC] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [KCC] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [KCC] SET QUERY_STORE = OFF
GO

ALTER DATABASE [KCC] SET  READ_WRITE 
GO

