
---------------------------------------------------------
-- SQL PRACTICE FILE
-- CHINOOK DATABASE
-- Created by Asma (Practice + Interview Prep)
---------------------------------------------------------

-- Always set the database first
USE Chinook;
GO


=========================================================
-- LEVEL 1: BASIC SELECT QUERIES
=========================================================

/*
Q1: Get the first 10 rows from the Track table.*/
SELECT TOP 10 *
FROM TRACK;
GO


/* Q2:Show Name, Composer, UnitPrice of all tracks.*/
SELECT NAME, Composer,UnitPrice from Track; 
GO


/*Q3:Write a query to find the total number of tracks.*/
select count(*) from Track;
GO
--4503

/* Q4:Get all tracks where UnitPrice is more than 0.99.*/
select * from Track where UnitPrice>0.99;
GO

/*Q5:Find all albums released by the Artist ‘Queen’*/
select Ar.ArtistId, Ar.Name,al.Title
from Artist Ar
join Album Al on
Ar.ArtistId = Al.ArtistId
where Name='Queen';


select * from Album;

/*
Q6:List all artists whose name starts with ‘A’
*/
SELECT ArtistId, Name
FROM Artist
WHERE Name LIKE 'A%';
GO


/*
Q7:List all artists whose name starts with ‘A’ with case sensitive
*/
SELECT ArtistId, Name
FROM Artist
WHERE lower(Name) LIKE 'a%';
GO


/*
Q8:Show all albums along with their Artist names
*/
SELECT ar.ArtistId, ar.Name AS ArtistName, al.AlbumId, al.Title AS AlbumTitle
FROM Album al
JOIN Artist ar ON al.ArtistId = ar.ArtistId
ORDER BY ar.ArtistId, al.AlbumId;
GO


/*
Q9:Find all tracks whose UnitPrice is greater than 0.99
*/
SELECT TrackId, Name AS TrackName, UnitPrice
FROM Track
WHERE UnitPrice > 0.99
ORDER BY UnitPrice DESC;

GO


/*
Q10:Count how many tracks are in each Album
*/
SELECT al.AlbumId, al.Title AS AlbumTitle, COUNT(t.TrackId) AS TrackCount
FROM Album al
LEFT JOIN Track t ON al.AlbumId = t.AlbumId
GROUP BY al.AlbumId, al.Title
ORDER BY TrackCount DESC, al.Title;
GO


/*
Q11:Find the total number of customers from each Country
*/
SELECT Country, COUNT(CustomerId) AS CustomerCount
FROM Customer
GROUP BY Country
ORDER BY CustomerCount DESC, Country;
GO
=========================================================
-- LEVEL 3: GROUP BY QUERIES
=========================================================

/*
Q11:— Find all customers who are from India or USA.
*/
SELECT CustomerId,FirstName,LastName, Country 
From Customer 
where Country IN('INDIA','USA');

GO


/*
Q12:Display InvoiceId, InvoiceDate, Customer FirstName, Customer LastName.
*/
SELECT I.InvoiceId, I.InvoiceDate, C.FirstName, C.LastName
from Customer C
Join Invoice I
ON C.CustomerID=I.CustomerID;
GO


/*
Q13:Find all employees who report to someone (ReportsTo is NOT NULL)
*/
SELECT EmployeeId, FirstName, LastName, Title, ReportsTo
from Employee 
where ReportsTo IS NOT NULL;
GO


/*
Q14:Show the number of invoices generated by each customer.
*/
SELECT c.CustomerId, c.FirstName, c.LastName, Count(I.InvoiceId) as InvoiceCount
From Customer c
Join Invoice I
ON c.CustomerId=I.CustomerId
group by c.CustomerId, c.FirstName, c.LastName;
GO


/*
Q15:Show the number of invoices generated by each customer.
SQL Rule (for GROUP BY queries):

If a column appears in the SELECT list, it must either:
✔ be inside an aggregate function, OR
✔ be included in the GROUP BY clause.
🔥 Memory Trick (Codey Style):

📌 SELECT column must be either:

Category	Rule
🧮 Number/Count/Sum	→ Must use Aggregate
🏷 Text/String/Date (not aggregated)	→ Must go in GROUP BY
🚀 Using OVER()	→ GROUP BY not required
*/
SELECT 
    c.CustomerId,
    c.FirstName,
    c.LastName,
    COUNT(i.InvoiceId) OVER (PARTITION BY c.CustomerId) AS InvoiceCount
FROM Customer c
JOIN Invoice i ON c.CustomerId = i.CustomerId;
GO
/*Summary Rule To Remember:

GROUP BY only matters when you use aggregate functions along with non-aggregated columns.
SELECT CustomerId, FirstName, LastName, Country 
FROM Customer 
WHERE Country IN ('India', 'USA');
is perfect, because you're:

Filtering rows

Not doing any aggregation

Not grouping data
*/

/*
Q16:List all customers who live in Brazil.
*/
SELECT *
FROM Customer
WHERE Country = 'Brazil';
GO


/*
Q17:List all customers who live in Brazil.*/
*/
SELECT 
    CustomerId, 
    FirstName, 
    LastName, 
    Country
FROM Customer
WHERE Country = 'Brazil';
GO


/*
Q18:Show all tracks where the AlbumId is 10.
*/
Select TrackId,
Name,
AlbumId
from Track
where AlbumId=10;
GO


/*
Q19:Find all employees whose Title contains the word 'Manager'.
*/
Select EmployeeId,
LastName,
FirstName,
Title
from Employee
where Title LIKE '%Manager%';
GO
select * from Employee;

/*
Q20:Show the first 10 tracks ordered by Name alphabetically.
*/
select TrackId,
Name
from Track
order by Name ASC LIMIT 10;
--this works perfect in MySQL server or sqlite, not in SQLServer--

select Top 20
TrackId,
Name
from Track
order by Name ASC;

/*List all invoices with total amount greater than 10.*/
select InvoiceID,
Total
from INVOICE
where Total>10
order by Total DESC;


GO=========================================================
-- LEVEL 4: SUBQUERY PRACTICE
=========================================================


=========================================================
-- LEVEL 5: INTERVIEW-STYLE QUESTIONS
=========================================================

/*
Q21:
*/
-- Your Query:
GO


/*
Q22:
*/
-- Your Query:
GO


/*
Q23:
*/
-- Your Query:
GO


/*
Q24:
*/
-- Your Query:
GO


/*
Q25:
*/
-- Your Query:
GO



---------------------------------------------------------
-- END OF PRACTICE FILE
---------------------------------------------------------

