--AGGREGATE functions
SELECT *
FROM PRODUCTS_1    

SELECT
	SUM(SALES) AS SALES_AMOUNT,
	MAX(SALES) AS MAXIMUM_AMOUNT,
	MIN(SALES) AS MINIMUM_AMOUNT
FROM PRODUCTS_1

==========================
SELECT
	--SUM(SALES) AS SALES_AMOUNT,
	MAX(SALES) AS MAXIMUM_AMOUNT,
	--MIN(SALES) AS MINIMUM_AMOUNT
	PNAME
FROM PRODUCTS_1
GROUP BY PNAME