create database Practice_DB

use Practice_DB

CREATE TABLE EMPLOYEES(ENO INT,ENAME VARCHAR(20),SALARY MONEY,DNO INT)

select * from EMPLOYEES

-- HOW TO SEE THE TABLE STRUCTURE
SP_HELP EMPLOYEES

-- ALTER
-- how to change the Data type of the Columns
ALTER TABLE EMPLOYEES ALTER COLUMN ENO BIGINT

-- HOW TO CHANGE THE SIZE OF THE COLUMNS
ALTER TABLE EMPLOYEES ALTER COLUMN ENAME VARCHAR(50)

-- ADD
-- HOW TO ADD THE COLUMNS TO AN EXSITING TABLES
ALTER TABLE EMPLOYEES ADD JOB VARCHAR(20)

-- to add multiple columns in eable just separte it with comma.
ALTER TABLE EMPLOYEES ADD location VARCHAR(30),job_location varchar(20)

-- DROP
-- HOW TO REMOVE THE COLUMNS FROM AN EXISTING TABLE
ALTER TABLE EMPLOYEES DROP COLUMN JOB_LOCATION

SELECT * FROM EMPLOYEES
--We get output of only headers as we have no data in the employees table. we havent inserted data still.

DROP TABLE EMPLOYEES

DROP DATABASE Practice_DB