--COMPARISON OPERATORS
--------------------

SELECT * FROM PRODUCTS

/*Result:
PID	PNAME	QUANTITY	COST	SALES
1	MOBILES	4	300	500
2	LAPTOPS	5	500	600
3	MOUSES	2	150	200*/

-- WRITE A QUERY TO GET ALL THE PRODUCT DETAILS WHERE PRODUCT='MOBILE'
SELECT * FROM PRODUCTS WHERE PNAME='MOBILES'
/*Result:
PID	PNAME	QUANTITY	COST	SALES
1	MOBILES	4	300	500*/
------------------------------------------
-- WRITE A QUERY TO GET THE PRODUCT DETAILS WHERE PRODUCT<>'MOBILE'
SELECT * FROM PRODUCTS WHERE PNAME<>'MOBILES'
/*Result:
PID	PNAME	QUANTITY	COST	SALES
2	LAPTOPS	5	500	600
3	MOUSES	2	150	200*/
----------------------------------------------
-- WRITE A QUERY TO GET THE PRODUCT DETAILS WHERE COST>300
SELECT * FROM PRODUCTS WHERE COST>300
/*Result:
PID	PNAME	QUANTITY	COST	SALES
2	LAPTOPS	5	500	600*/

-------------------------------------------
-- WRITE A QUERY TO GET THE PRODUCT DETAILS WHERE COST<300
SELECT * FROM PRODUCTS WHERE COST<300
/*Result:
PID	PNAME	QUANTITY	COST	SALES
3	MOUSES	2	150	200*/
----------------------------------------------
-- WRITE A QUERY TO GET THE PRODUCT DETAILS WHERE COST>=300
SELECT * FROM PRODUCTS WHERE COST>=300
/*Result:
PID	PNAME	QUANTITY	COST	SALES
1	MOBILES	4	300	500
2	LAPTOPS	5	500	600*/

----------------------------------------------

-- WRITE A QUERY TO GET THE PRODUCT DETAILS WHERE COST<=350
SELECT * FROM PRODUCTS WHERE COST<=350
/*Result:
PID	PNAME	QUANTITY	COST	SALES
1	MOBILES	4	300	500
3	MOUSES	2	150	200*/