
--HAVING
--WHERE

SELECT 
	--SUM(SALES) AS SALES_AMOUNT,
	MAX(SALES) AS HIGHESTSALES, --MAXIMUM_AMOUNT,
	--MIN(SALES) AS MINIMUM_AMOUNT
	PNAME

FROM PRODUCTS_1
GROUP BY PNAME
HAVING MAX(SALES)>=600

--WHERE MAX(SALES)>=600

DIFFERENCE BETWEEN WHERE AND HAVING

WHERE               HAVING
FILTER ROWS         FILTER ROWS
SELECT              GROUP BY
INDIVIDUAL ROWS      AGGREGATED/GROUP DATA
BEFORE AGGREGATION  AFTER AGGREGATION


EXECUTION FLOW:

FROM -- WHERE -- GROUPBY -- HAVING -- SELECT