
CREATE TABLE PRODUCTS(PID INT,PNAME VARCHAR(20),QUANTITY INT,COST INT,SALES INT)

INSERT INTO PRODUCTS VALUES(201,'PC',5,400,600)
INSERT INTO PRODUCTS VALUES(202,'CHARGER',5,500,600)
INSERT INTO PRODUCTS VALUES(203,'MONITOR',3,250,300)
INSERT INTO PRODUCTS VALUES(203,'MONITOR',3,250,300)

select * from products
===========================
CREATE TABLE PRODUCTS_1(PID INT,PNAME VARCHAR(20),QUANTITY INT,COST INT,SALES INT)

INSERT INTO PRODUCTS_1 VALUES(1,'PC',4,300,500)
INSERT INTO PRODUCTS_1 VALUES(102,'CHARGER',5,500,600)
INSERT INTO PRODUCTS_1 VALUES(103,'MONITOR',2,150,200)

select * from PRODUCTS_1
=====================
--UNION ALL
SELECT *
FROM PRODUCTS
UNION ALL
SELECT *
FROM PRODUCTS_1

===================================
--UNION
SELECT *
FROM PRODUCTS

UNION 

SELECT *
FROM PRODUCTS_1

=================================
--INTERSECT

SELECT *

FROM PRODUCTS
INTERSECT 
SELECT *

FROM PRODUCTS_1
--output is only headers, as we dont have any common records between them.
==================================
--EXCEPT
SELECT *

FROM PRODUCTS
EXCEPT 
SELECT *

FROM PRODUCTS_1

=========
--EXCEPT


SELECT *

FROM PRODUCTS_1
EXCEPT

SELECT *

FROM PRODUCTS

==============================================

SELECT *

FROM PRODUCTS_1
ORDER BY QUANTITY ASC
==========================================
SELECT *

FROM PRODUCTS_1
ORDER BY COST DESC

=============================
SELECT *

FROM PRODUCTS ---ORDER BY COST
UNION ALL

SELECT * 
FROM PRODUCTS

UNION ALL
SELECT *

FROM PRODUCTS_1 ORDER BY COST   -- 18

