-- TRUNCATE
TRUNCATE TABLE EMPLOYEES
use Practice_DB

CREATE TABLE EMP(ENO INT,ENAME VARCHAR(20),JOB VARCHAR(20),SALARY INT,DNO INT)

-- INSERT
INSERT INTO EMP VALUES(101,'WARNER','DEV',12000,10)
INSERT INTO EMP VALUES(102,'SMITH','SALES',14000,20)
INSERT INTO EMP VALUES(103,'SCOOT','ADMIN',16000,30)
INSERT INTO EMP VALUES(104,'FINCH','DEV',18000,10)
INSERT INTO EMP VALUES(105,'STARCH','SALES',20000,20)
INSERT INTO EMP VALUES(106,'MAXWELL','DEV',21000,10)

INSERT INTO EMP (ENO,ENAME,SALARY) VALUES(107,'ABD',22000)

SELECT * FROM EMP

-- UPDATE
UPDATE EMP SET SALARY=30000

UPDATE EMP SET SALARY=30000 WHERE ENO=101

UPDATE EMP SET SALARY=25000,DNO=20 WHERE ENO=103

UPDATE EMP SET JOB='ADMIN',SALARY=35000,DNO=30 WHERE ENO=105

-- DELETE
DELETE FROM EMP

DELETE FROM EMP WHERE ENO=105

-- SELECT

SELECT * FROM EMP

SELECT ENO,ENAME,SALARY FROM EMP

-- WHERE
SELECT ENO,ENAME,JOB,SALARY FROM EMP WHERE ENO=101

SELECT * FROM EMP WHERE DNO=10

-- DIFFERENT WAYS TO SELECT THE DATA FROM THE TABLES

SELECT * FROM EMP						-- ONE PART NAME
SELECT * FROM DBO.EMP						-- TWO PART NAME
SELECT * FROM Practice_DB.DBO.EMP			        -- THREE PART NAME
SELECT * FROM Server.Practice_DB.DBO.EMP                        -- Four Part Name